[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.95
decorations = "Full"
title = "Alacritty Terminal"

[font]
size = 13.0
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold" }
[colors.primary]
foreground = "#d8d8d8"
background = "#181818"

[keyboard]
# Example of a custom key binding: Ctrl+Shift+Enter to spawn a new instance
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]

[general]
# Import additional configuration files
# import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/tokyo_night.toml"
]
